### PR TITLE
Cucumber Expressions - parameter types

### PR DESCRIPTION
**Pull request by tetiana12345678**
PR to implement cucumber expressions parameter types.

Parameter Type | Description
-- | --
{int} | Matches integers, for example 71 or -19.
{float} | Matches floats, for example 3.6, .8 or -9.2.
{word} | Matches words without whitespace, for example banana (but not banana split)
{string} | Matches single-quoted or double-quoted strings, for example "banana split" or 'banana split'(but not banana split). Only the text between the quotes will be extracted. The quotes themselves are discarded.

More about cucumber expressions can be found here https://docs.cucumber.io/cucumber/cucumber-expressions/

### CODE REVIEW

**Comment by frahugo** [comment]
@tetiana12345678 @nicholasjhenry I wouldn't mind another pair or eyes looking at my changes. Hopefuly I improved the readability.

**Comment by revati** [comment]
Maybe I'm wrong, and correct me if I am, but it seems that there are only predefined types.

It would be great to have the option for the developer to define custom types if needed.

```
type :age, ~r/(+d){2}/, resolve: &String.to_integer/1
```

It would unleash great extension capabilities. I think the library shouldn't be able to do everything, but it should give user the ability to extend itself if needed.

**Comment by hauleth** [comment]
@revati I agree, however the question is how it should be implemented. Should user defined matches be defined globally or per feature file?

**Comment by revati** [comment]
As with `import_steps` and `import_tags` there also would be `import_captures` or something like that

**Comment by nicholasjhenry** [comment]
@revati This PR is the first step in a development plan outlined here:

https://github.com/cabbage-ex/cabbage/issues/47#issue-327392851

> 1. support parameter types
> 2. support optional text, alternative text, escaping
> 3. support custom parameter types

What you described:

> It would be great to have the option for the developer to define custom types if needed.

would be step 3.

As mentioned in my previous post https://github.com/cabbage-ex/cabbage/issues/64#issuecomment-467984631, I can resolve the merge conflicts, but won't be doing anything else beyond in this PR.

**Comment by revati** [comment]
Yes, in that case, if there are planned next two steps, it seems to be ok

**Pull request merged**
